export const REDIRECT_URI = "redirectUri";
export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const PLAN_SELECTED = "PLAN_SELECTED";
export const IMAGES_POST_DATA = "IMAGES_POST_DATA";
export const PAYMENT_REQUIRED_ERR_MESSAGE = "payment_required";

export const states = [
     { code: 'AP', name: 'Andhra Pradesh' },
     { code: 'AR', name: 'Arunachal Pradesh' },
     { code: 'AS', name: 'Assam' },
     { code: 'BR', name: 'Bihar' },
     { code: 'CT', name: 'Chhattisgarh' },
     { code: 'GA', name: 'Goa' },
     { code: 'GJ', name: 'Gujarat' },
     { code: 'HR', name: 'Haryana' },
     { code: 'HP', name: 'Himachal Pradesh' },
     { code: 'JH', name: 'Jharkhand' },
     { code: 'KA', name: 'Karnataka' },
     { code: 'KL', name: 'Kerala' },
     { code: 'MP', name: 'Madhya Pradesh' },
     { code: 'MH', name: 'Maharashtra' },
     { code: 'MN', name: 'Manipur' },
     { code: 'ML', name: 'Meghalaya' },
     { code: 'MZ', name: 'Mizoram' },
     { code: 'NL', name: 'Nagaland' },
     { code: 'OR', name: 'Odisha' },
     { code: 'PB', name: 'Punjab' },
     { code: 'RJ', name: 'Rajasthan' },
     { code: 'SK', name: 'Sikkim' },
     { code: 'TN', name: 'Tamil Nadu' },
     { code: 'TG', name: 'Telangana' },
     { code: 'TR', name: 'Tripura' },
     { code: 'UP', name: 'Uttar Pradesh' },
     { code: 'UT', name: 'Uttarakhand' },
     { code: 'WB', name: 'West Bengal' },
     { code: 'AN', name: 'Andaman and Nicobar Islands' },
     { code: 'CH', name: 'Chandigarh' },
     { code: 'DH', name: 'Dadra and Nagar Haveli and Daman and Diu' },
     { code: 'LD', name: 'Lakshadweep' },
     { code: 'DL', name: 'Delhi' },
     { code: 'PY', name: 'Puducherry' },
];


export const districts = [
     { code: 'AG', name: 'Agar Malwa' },
     { code: 'AL', name: 'Alirajpur' },
     { code: 'AN', name: 'Anuppur' },
     { code: 'AK', name: 'Ashoknagar' },
     { code: 'BG', name: 'Balaghat' },
     { code: 'BW', name: 'Barwani' },
     { code: 'BT', name: 'Betul' },
     { code: 'BD', name: 'Bhind' },
     { code: 'BP', name: 'Bhopal' },
     { code: 'BH', name: 'Burhanpur' },
     { code: 'CT', name: 'Chhatarpur' },
     { code: 'CN', name: 'Chhindwara' },
     { code: 'DM', name: 'Damoh' },
     { code: 'DT', name: 'Datia' },
     { code: 'DW', name: 'Dewas' },
     { code: 'DH', name: 'Dhar' },
     { code: 'DI', name: 'Dindori' },
     { code: 'GN', name: 'Guna' },
     { code: 'GW', name: 'Gwalior' },
     { code: 'HD', name: 'Harda' },
     { code: 'HB', name: 'Hoshangabad' },
     { code: 'ID', name: 'Indore' },
     { code: 'JB', name: 'Jabalpur' },
     { code: 'JH', name: 'Jhabua' },
     { code: 'KT', name: 'Katni' },
     { code: 'KW', name: 'Khandwa' },
     { code: 'KG', name: 'Khargone' },
     { code: 'MD', name: 'Mandla' },
     { code: 'MS', name: 'Mandsaur' },
     { code: 'MR', name: 'Morena' },
     { code: 'NP', name: 'Narsinghpur' },
     { code: 'NH', name: 'Neemuch' },
     { code: 'PN', name: 'Panna' },
     { code: 'RS', name: 'Raisen' },
     { code: 'RG', name: 'Rajgarh' },
     { code: 'RL', name: 'Ratlam' },
     { code: 'RW', name: 'Rewa' },
     { code: 'SG', name: 'Sagar' },
     { code: 'SN', name: 'Satna' },
     { code: 'SH', name: 'Sehore' },
     { code: 'SE', name: 'Seoni' },
     { code: 'SD', name: 'Shahdol' },
     { code: 'SP', name: 'Shajapur' },
     { code: 'SO', name: 'Sheopur' },
     { code: 'SV', name: 'Shivpuri' },
     { code: 'SI', name: 'Sidhi' },
     { code: 'SR', name: 'Singrauli' },
     { code: 'TK', name: 'Tikamgarh' },
     { code: 'UJ', name: 'Ujjain' },
     { code: 'UM', name: 'Umaria' },
     { code: 'VD', name: 'Vidisha' },
];
